// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALI-fTKR3iXE_rJR5n5NDyXA7gsowMMrc',
    appId: '1:474645244163:web:1b40e53d8531121e9f2136',
    messagingSenderId: '474645244163',
    projectId: 'aaaa-ee97d',
    authDomain: 'aaaa-ee97d.firebaseapp.com',
    storageBucket: 'aaaa-ee97d.appspot.com',
    measurementId: 'G-M16LFB93FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYiUE4a9DbWbkoiJYcTpbvd5pUh7ejwuk',
    appId: '1:474645244163:android:d335144b87b74bc69f2136',
    messagingSenderId: '474645244163',
    projectId: 'aaaa-ee97d',
    storageBucket: 'aaaa-ee97d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBo4koe5koFUeUHqZPj6NvaKLQ-h6JM4',
    appId: '1:474645244163:ios:b5a15028e31093549f2136',
    messagingSenderId: '474645244163',
    projectId: 'aaaa-ee97d',
    storageBucket: 'aaaa-ee97d.appspot.com',
    iosBundleId: 'com.example.aaaaaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdBo4koe5koFUeUHqZPj6NvaKLQ-h6JM4',
    appId: '1:474645244163:ios:9840596e379878269f2136',
    messagingSenderId: '474645244163',
    projectId: 'aaaa-ee97d',
    storageBucket: 'aaaa-ee97d.appspot.com',
    iosBundleId: 'com.example.aaaaaa.RunnerTests',
  );
}
